config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  mount Sidekiq::Web => "/sidekiq"

  resources :collections do
    resources :assets do
    member do
      get 'direct'
      get 'redirect'
    end
    end
    member do
      get 'ranking'
      get 'leaderboard'
    end
  end

  resources :votes
  resources :wallets
  resources :admin

  get '/votes/:winner/:loser', to: 'votes#battle', as: 'votes_battle'

  get '/search', to: 'pages#search', as: 'search'
  get '/leaderboard', to: 'pages#leaderboard', as: 'leaderboard'
  get '/submit-project', to: 'pages#submit', as: 'submit'
  get '/giveaway', to: 'pages#giveaway', as: 'giveaway'

  root "collections#index"

  post "/session", to: "session#create"

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  # Almost every application defines a route for the root path ("/") at the top of this file.
  # root "articles#index"
end

app/models/collection.rb
class Collection < ApplicationRecord
  has_many :assets
  has_many :votes
  has_many :rankings
  has_many :events

  def rank_confidence
    raw_confidence = self.assets.left_outer_joins(:ranking).average('rankings.progress')
  end

  def percentage_voted
    votes = self.votes.pluck(:winner_id, :loser_id)
    total_votes = votes.flatten(1).uniq.count
    raw_percent = (total_votes.to_f / self.assets.count).to_f * 100
    
    raw_percent >= 100 ? 100.to_i : raw_percent
  end
end

app/controllers/collections_controller.rb
class CollectionsController < ApplicationController
  before_action :get_collection, except: [:index]

  def index
    @collections = Collection.all.order(name: :asc)

    respond_to do |format|
      format.html
      format.json { render json: { collections: @collections } }
    end
  end

  def show
    compare = @collection.assets.left_outer_joins(:ranking).where.not(image_url: nil).order(Arel.sql("(1 - (rankings.votes_count :: DECIMAL / MAX((rankings.votes_count+1) * 100) OVER())) * (floor(random() * 40 + 1) :: int) desc")).limit(25)

    if compare.size < 10
      compare = @collection.assets.left_outer_joins(:ranking).where.not(image_url: nil).order(Arel.sql("(1 - (rankings.votes_count :: DECIMAL / MAX((rankings.votes_count+1) * 100) OVER())) * (floor(random() * 40 + 1) :: int) desc")).limit(50)
    end

    @item_first = compare.sample
    @item_last = compare.sample
    @next_first = compare.sample
    @next_last = compare.sample

    if @current_wallet.present?
      @recent_vote_count = @collection.votes.where('wallet_id = ? AND created_at > ?', @current_wallet.id, Time.current - 60.minutes).count
    else
      @recent_vote_count = @collection.votes.where('ip_address = ? AND created_at > ?', request.remote_ip, Time.current - 60.minutes).count
    end

    @vote_throttle = @recent_vote_count > 300 ? true : false
    
    respond_to do |format|
      format.html
      format.json { render json: { collection: @collection.attributes.except('traits'), total_items: @collection.assets.count, total_votes: @collection.votes.count, percent_done: @collection.percentage_voted, rank_confidence: @collection.rank_confidence, item_first: @item_first.attributes.except('traits'), item_last: @item_last.attributes.except('traits'), next: {next_first: @next_first.attributes.except('traits'), next_last: @next_last.attributes.except('traits')} } }
    end

    if @item_first == @item_last or @item_first.blank? or @item_last.blank? 
      redirect_to collection_path(@collection.slug)
    end
  end

  def ranking
    @assets = @collection.assets

    if params[:trait].present?
      params[:trait].each do |trait|
        @assets = @assets.left_outer_joins(:ranking).where('traits @> ?', [{trait_type: trait['type']}, {value: trait['value']}].to_json)
      end
    end

    @assets = @assets.left_outer_joins(:ranking).where('rankings.rank > 0').order('rankings.rank ASC').page params[:page]

    respond_to do |format|
      format.html
      format.json { render json: { collection: @collection, total_items: @collection.assets.count, total_votes: @collection.votes.count, percent_done: @collection.percentage_voted, rank_confidence: @collection.rank_confidence, assets: @assets } }
    end
  end

  def leaderboard
    @discord = Discordrb::Bot.new(token: ENV['DISCORD'])

    @leaders = Rails.cache.fetch(["v2","query-leaders-#{@collection.id}"], expires_in: 1.hour) do
      @collection.votes.where("wallet_id IS NOT NULL OR discord_user_id IS NOT NULL").group(:wallet_id, :discord_user_id).order(count_all: :desc).count.first(100)
    end
  end

private
  def get_collection
    if /\A0x[a-fA-F0-9]{40}\z/i.match(params[:id])
      @collection = Collection.where(address: params[:id]).first
      redirect_to ranking_collection_path(@collection.slug)
    else
      @collection = Collection.where(slug: params[:id]).first
    end
  end

end

app/helpers/collections_helper.rb
module CollectionsHelper
  def trait_rarity(collection_total, trait_total)
    percentage = ((trait_total.to_f / collection_total.to_f) * 100).round(1)
    percentage.to_s + "%"
  end
end

app/views/collections/_confidence_note.html.erb
<% if @collection.rank_confidence < 100 %>
<div class="rounded-md bg-yellow-50 p-4 my-4">
  <div class="flex">
    <div class="flex-shrink-0">
      <!-- Heroicon name: solid/exclamation -->
      <svg class="h-5 w-5 text-yellow-400" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
        <path fill-rule="evenodd" d="M8.257 3.099c.765-1.36 2.722-1.36 3.486 0l5.58 9.92c.75 1.334-.213 2.98-1.742 2.98H4.42c-1.53 0-2.493-1.646-1.743-2.98l5.58-9.92zM11 13a1 1 0 11-2 0 1 1 0 012 0zm-1-8a1 1 0 00-1 1v3a1 1 0 002 0V6a1 1 0 00-1-1z" clip-rule="evenodd" />
      </svg>
    </div>
    <div class="ml-3">
      <h3 class="text-sm font-medium text-yellow-800">
        Note about score & ranking
      </h3>
      <div class="mt-2 text-sm text-yellow-700">
        <p>
          This project is still in the initial ranking phase. Until Ranking Confidence reaches 100%, the rank of any given item may change quite a bit.
        </p>
      </div>
    </div>
  </div>
</div>
<% end %>

app/views/collections/leaderboard.html.erb
<% title "#{@collection.name} NFT Leaderboard" %>
<header class="bg-white shadow">
  <div class="px-4 py-6 mx-auto max-w-7xl sm:px-6 lg:px-8">
    <div class="md:flex md:items-center md:justify-between md:space-x-5">
      <div class="flex items-start space-x-5">
        <div class="flex-shrink-0">
          <div class="relative">
            <img class="w-16 h-16 rounded-full" src="<%= @collection.image_url %>" alt="">
            <span class="absolute inset-0 rounded-full shadow-inner" aria-hidden="true"></span>
          </div>
        </div>
        <div class="pt-2.5">
          <h1 class="text-4xl font-bold text-gray-900"><%= @collection.name %></h1>
        </div>
        <div class="py-3 pl-5">
          <nav class="flex space-x-4" aria-label="Tabs">
            <!-- Current: "bg-indigo-100 text-indigo-700", Default: "text-gray-500 hover:text-gray-700" -->
            <a href="<%= collection_path(@collection.slug) %>" class="px-3 py-2 text-sm font-medium text-gray-500 rounded-md hover:text-gray-700">
              Battle
            </a>

            <a href="<%= ranking_collection_path(@collection.slug) %>" class="px-3 py-2 text-sm font-medium text-gray-500 rounded-md hover:text-gray-700">
              Rankings
            </a>

            <a href="<%= leaderboard_collection_path(@collection.slug) %>" class="px-3 py-2 text-sm font-medium text-gray-500 text-indigo-700 bg-indigo-100 rounded-md hover:text-gray-700">
              Leaderboard
            </a>
          </nav>
        </div>
      </div>
      <div class="flex my-2">
        <%= render "links" %>
      </div>
    </div>
  </div>
</header>
<main>
  <div class="max-w-5xl pb-6 mx-auto sm:px-6 lg:px-8">

    <div class="px-4 pb-4 mt-4 sm:px-0">

      <% if !@current_wallet.present? %>
      <div class="p-4 mb-4 border-2 border-indigo-400 rounded-md bg-indigo-50">
        <div class="flex">
          <div class="flex-shrink-0">
            <!-- Heroicon name: solid/information-circle -->
            <svg class="text-indigo-400 h-7 w-7" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
              <path fill-rule="evenodd" d="M18 10a8 8 0 11-16 0 8 8 0 0116 0zm-7-4a1 1 0 11-2 0 1 1 0 012 0zM9 9a1 1 0 000 2v3a1 1 0 001 1h1a1 1 0 100-2v-3a1 1 0 00-1-1H9z" clip-rule="evenodd" />
            </svg>
          </div>
          <div class="flex-1 ml-3 md:flex md:justify-between">
            <p class="text-lg text-indigo-700">
              Connect your wallet to start working your way up the leaderboard!
            </p>
          </div>
        </div>
      </div>
      <% end %>

      <div class="flex flex-col">
        <div class="-my-2 overflow-x-auto sm:-mx-6 lg:-mx-8">
          <div class="inline-block min-w-full py-2 align-middle sm:px-6 lg:px-8">
            <div class="overflow-hidden border-b border-gray-200 shadow sm:rounded-lg">
              <table class="min-w-full divide-y divide-gray-200">
                <thead class="bg-gray-50">
                  <tr>
                    <th scope="col" class="px-6 py-3 text-xs font-medium tracking-wider text-left text-gray-500 uppercase">
                      <span class="sr-only">Position</span>
                    </th>
                    <th scope="col" class="px-6 py-3 text-xs font-medium tracking-wider text-left text-gray-500 uppercase">
                      User
                    </th>
                    <th scope="col" class="px-6 py-3 text-xs font-medium tracking-wider text-right text-gray-500 uppercase">
                      Votes
                    </th>
                  </tr>
                </thead>
                <tbody class="bg-white divide-y divide-gray-200">
                <% cache(['v4', "leaderboard-#{@collection.id}"], expires_in: 1.hours) do %>
                <% @leaders.each_with_index do |leader, index| %>
                  <tr>
                    <td class="w-px py-4 pl-6 text-sm text-center text-gray-400 whitespace-nowrap">
                      <%= index + 1 %>
                    </td>
                    <% 
                      if leader[0][0].present?
                        cache_name = "wallet-#{leader[0][0]}"
                      elsif leader[0][1].present?
                        cache_name = "discord-#{leader[0][1]}"
                      end

                      cache(['v3', "leaderboard-#{@collection.id}-#{cache_name}"], expires_in: 12.hours) do 
                    %>
                    <% wallet = Wallet.find(leader[0][0]) if leader[0][0].present? %>
                    <% discord_user = @discord.user(leader[0][1]) if leader[0][1].present? %>
                    <td class="px-6 py-4 whitespace-nowrap">
                      <div class="flex items-center">
                        <div class="flex-shrink-0 w-10 h-10">
                        <% if wallet.present? %>
                          <img src="https://abstract.cool/<%=wallet.address%>.png" class="inline w-10 h-10 mr-1 rounded-full" />
                        <% elsif discord_user.present? %>
                          <img src="<%=discord_user.avatar_url %>" class="w-10 h-10 rounded-full" />
                        <% end %>
                        </div>
                        <div class="ml-4">
                          <div class="text-sm font-medium text-gray-900">
                            <% if wallet.present? %>
                              <%= render partial: "shared/address", locals: {address: wallet.address} %>
                            <% elsif discord_user.present? %>
                              <%=discord_user.name %> <i class="ml-1 text-gray-300 fa-brands fa-discord"></i>
                            <% end %>
                          </div>
                        </div>
                      </div>
                    </td>
                    <% end %>
                    <td class="px-6 py-4 text-sm font-medium text-right whitespace-nowrap">
                      <span class="inline-flex px-6 py-3 text-lg font-semibold leading-5 text-green-800 bg-green-100 rounded-full"><%=leader[1]%></span>
                    </td>
                  </tr>
                  <% end %>
                  <% end %>
                </tbody>
              </table>
            </div>
          </div>
        </div>
      </div>

    </div>
  </div>
</main>

app/views/collections/ranking.html.erb
<% title "#{@collection.name} NFT Visual Ranking" %>
<header class="bg-white shadow">
  <div class="max-w-7xl mx-auto py-6 px-4 sm:px-6 lg:px-8">
    <div class="md:flex md:items-center md:justify-between md:space-x-5">
      <div class="flex items-start space-x-5">
        <div class="flex-shrink-0">
          <div class="relative">
            <img class="h-16 w-16 rounded-full" src="<%= @collection.image_url %>" alt="">
            <span class="absolute inset-0 shadow-inner rounded-full" aria-hidden="true"></span>
          </div>
        </div>
        <div class="pt-2.5">
          <h1 class="text-4xl font-bold text-gray-900"><%= @collection.name %></h1>
        </div>
        <div class="py-3 pl-5">
          <nav class="flex space-x-4" aria-label="Tabs">
            <!-- Current: "bg-indigo-100 text-indigo-700", Default: "text-gray-500 hover:text-gray-700" -->
            <a href="<%= collection_path(@collection.slug) %>" class="text-gray-500 hover:text-gray-700 px-3 py-2 font-medium text-sm rounded-md">
              Battle
            </a>

            <a href="<%= ranking_collection_path(@collection.slug) %>" class="bg-indigo-100 text-indigo-700  text-gray-500 hover:text-gray-700 px-3 py-2 font-medium text-sm rounded-md">
              Rankings
            </a>

            <a href="<%= leaderboard_collection_path(@collection.slug) %>" class="text-gray-500 hover:text-gray-700 px-3 py-2 font-medium text-sm rounded-md">
              Leaderboard
            </a>
          </nav>
        </div>
      </div>
      <div class="flex my-2">
        <%= render "links" %>
      </div>
    </div>
  </div>
</header>
<main>
  <div class="max-w-7xl mx-auto pb-6 sm:px-6 lg:px-8">
    <%= render "stats" %>

    <%= render "confidence_note" %>

    <% if params[:trait].present? %>
    <div class="my-5">
      <% params[:trait].each do |trait| %>
      <span class="inline-flex rounded-full items-center py-0.5 pl-3.5 pr-3 text-lg font-medium bg-indigo-100 text-indigo-700">
        <%=trait['type']%>: <%=trait['value']%>
        <a href="<%= ranking_collection_path(@collection.slug) %>" class="flex-shrink-0 ml-0.5 h-4 w-4 rounded-full inline-flex items-center justify-center text-indigo-400 hover:bg-indigo-200 hover:text-indigo-500 focus:outline-none focus:bg-indigo-500 focus:text-white">
          <span class="sr-only">Remove large option</span>
          <svg class="h-2 w-2" stroke="currentColor" fill="none" viewBox="0 0 8 8">
            <path stroke-linecap="round" stroke-width="1.5" d="M1 1l6 6m0-6L1 7" />
          </svg>
        </a>
      </span>
      <% end %>
    </div>
    <% end %>

    <div class="px-4 pb-4 sm:px-0">
      <div class="flex flex-col">
        <div class="-my-2 overflow-x-auto sm:-mx-6 lg:-mx-8">
          <div class="py-2 align-middle inline-block min-w-full sm:px-6 lg:px-8">
            <div class="shadow overflow-hidden border-b border-gray-200 sm:rounded-lg">
              <table class="min-w-full divide-y divide-gray-200">
                <thead class="bg-gray-50">
                  <tr>
                    <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                      <span class="sr-only">Position</span>
                    </th>
                    <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                      Asset
                    </th>
                    <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                      Current Price
                    </th>
                    <th scope="col" class="px-6 py-3 text-center text-xs font-medium text-gray-500 uppercase tracking-wider">
                      Score
                    </th>
                  </tr>
                </thead>
                <tbody class="bg-white divide-y divide-gray-200">

                  <% @assets.each do |asset| %>
                  <tr>
                    <td class="pl-6 py-4 whitespace-nowrap text-gray-400 text-sm w-px text-center">
                      <%= asset.ranking.rank %>
                    </td>
                    <td class="px-6 py-4 whitespace-nowrap">
                      <div class="flex items-center">
                        <div class="flex-shrink-0 h-20 w-20">
                        <a href="<%=collection_asset_path(@collection.slug, asset.token_id)%>">
                          <img class="h-20 w-20 rounded-lg" src="<%=asset.image_thumbnail_url%>" alt="">
                          </a>
                        </div>
                        <div class="ml-4 max-w-md">
                          <div class="text-lg font-medium text-gray-900 text-ellipsis truncate">
                            <a href="<%=collection_asset_path(@collection.slug, asset.token_id)%>" class="hover:text-indigo-500 "><%=asset.formatted_name%></a>
                          </div>
                          <div class="text-sm">
                            <a href="<%=asset.opensea_link %>" target="_blank">OpenSea</a> 
                            <% if asset.external_link.present? %>
                            - <a href="<%=asset.external_link %>" target="_blank">Project</a>
                            <% end %>
                          </div>
                        </div>
                      </div>
                    </td>
                    
                    <td class="px-6 py-4 whitespace-nowrap text-left text-sm font-medium w-56">
                    <% if asset.current_sale_price.present? and asset.current_sale_token.present? %>
                    <a href="<%=asset.opensea_link %>" target="_blank">
                      <%= asset.current_sale_price.to_f / (10**asset.current_sale_token_decimals) %> <%=asset.current_sale_token %> <i class="fa-duotone fa-sack-dollar text-green-500"></i>
                    </a>
                    <% end %>
                    </td>
                    <td class="px-6 py-4 whitespace-nowrap text-center text-sm font-medium w-px">
                      <p class="py-3 px-6 inline-flex text-lg leading-5 font-semibold rounded-full bg-green-100 text-green-800">
                        <%=asset.ranking.elo_rating.round %>
                      </p>
                      <p class="text-xs text-gray-400 pt-1"><%= pluralize(asset.ranking.votes_count, 'vote') %></p>
                    </td>
                  </tr>
                  <% end %>
                </tbody>
              </table>
            </div>

            <%= paginate @assets, window: 1, outer_window: 3 %>

          </div>
        </div>
      </div>
    </div>
  </div>
</main>

app/views/collections/show.html.erb
<% title "#{@collection.name} NFT Visual Battle" %>
<% meta_image(@collection.image_url.sub('s120', 's600')) if @collection.image_url.present? %>

<header class="bg-white shadow">
  <div class="max-w-7xl mx-auto py-6 px-4 sm:px-6 lg:px-8">
    <div class="md:flex md:items-center md:justify-between md:space-x-5">
      <div class="flex items-start space-x-5 flex-wrap">
        <div class="flex-shrink-0">
          <div class="relative">
            <img class="h-16 w-16 rounded-full" src="<%= @collection.image_url %>" alt="">
            <span class="absolute inset-0 shadow-inner rounded-full" aria-hidden="true"></span>
          </div>
        </div>

        <div class="pt-2.5">
          <h1 class="text-4xl font-bold text-gray-900"><%= @collection.name %></h1>
        </div>
    
        <div class="py-3 pl-5">
          <nav class="flex space-x-4" aria-label="Tabs">
            <a href="<%= collection_path(@collection.slug) %>" class="bg-indigo-100 text-indigo-700 text-gray-500 hover:text-gray-700 px-3 py-2 font-medium text-sm rounded-md">
              Battle
            </a>

            <a href="<%= ranking_collection_path(@collection.slug) %>" class="text-gray-500 hover:text-gray-700 px-3 py-2 font-medium text-sm rounded-md">
              Rankings
            </a>

            <a href="<%= leaderboard_collection_path(@collection.slug) %>" class="text-gray-500 hover:text-gray-700 px-3 py-2 font-medium text-sm rounded-md">
              Leaderboard
            </a>
          </nav>
        </div>
        
        
      </div>
      <div class="flex my-2">
        <%= render "links" %>
      </div>
    </div>
  </div>
</header>
<main>
  <%= turbo_frame_tag "choose_image" do %>
  <div class="max-w-7xl mx-auto pb-6 sm:px-6 lg:px-8">
    
    <%= render "stats" %>

    <% if !@current_wallet.present? %>
    <div class="rounded-md bg-indigo-50 p-4 mb-4 border-2 border-indigo-400 mx-2 md:mx-0 hidden md:block">
      <div class="flex">
        <div class="flex-shrink-0">
          <svg class="h-7 w-7 text-indigo-400" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
            <path fill-rule="evenodd" d="M18 10a8 8 0 11-16 0 8 8 0 0116 0zm-7-4a1 1 0 11-2 0 1 1 0 012 0zM9 9a1 1 0 000 2v3a1 1 0 001 1h1a1 1 0 100-2v-3a1 1 0 00-1-1H9z" clip-rule="evenodd" />
          </svg>
        </div>
        <div class="ml-3 flex-1 md:flex md:justify-between">
          <p class="text-lg text-indigo-700">
            Connect your wallet to start working your way up the leaderboard!
          </p>
        </div>
      </div>
    </div>
    <% end %>

    <div class="pb-4 sm:px-0 relative px-2 md:px-0">
      
      <div class="bg-white overflow-hidden shadow rounded-lg relative">
        <% if @vote_throttle %>
        <div class="absolute w-full bg-white bg-opacity-75" style="z-index:10000" aria-labelledby="modal-title" role="dialog" aria-modal="true">
          <div class="flex items-start justify-start h-screen pt-20 px-4 pb-10 mt-28 text-center sm:block sm:p-0">

            <span class="hidden inline-block align-middle" aria-hidden="true">&#8203;</span>

            <div class="inline-block align-top bg-white rounded-lg px-4 mt-10 pb-4 text-center overflow-hidden shadow-xl transform transition-all sm:my-8 sm:align-middle sm:max-w-sm sm:w-full sm:p-6">
              <div>
                <div class="mx-auto flex items-center text-center justify-center h-20 w-20 rounded-full">
                  <i class="fa-duotone fa-igloo h-20 w-20 text-blue-500"></i>
                </div>
                <div class="mt-3 text-center sm:mt-5">
                  <h3 class="text-xl leading-4 font-bold text-gray-900" id="modal-title">
                    Cooldown Period
                  </h3>
                  <div class="mt-2">
                    <p class="text-md text-gray-500 mb-3">
                      You're doing an amazing job battling <%= @collection.name %>, with <b><%= @recent_vote_count %> battles</b> in the past hour! 
                    </p>
                    <p class="text-xs text-gray-500">To keep the rankings for this collection balanced, you'll need to take a little break and check out some other collections for a few minutes!</p>
                  </div>
                </div>
              </div>
              <div class="mt-5 sm:mt-6">
                <a href="/" target="_top" class="inline-flex justify-center w-full rounded-md border border-transparent shadow-sm px-4 py-2 bg-indigo-600 text-base font-medium text-white hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500 sm:text-sm">
                  View other collections
                </a>
              </div>
            </div>
          </div>
        </div>
        <% end %>

        <div class="px-4 pt-7 sm:px-6">
          <h2 class="text-3xl md:text-4xl font-bold text-gray-900 text-center">Which one do you like more?</h2>
        </div>
        
        <div class="px-2 md:px-4 p-0 sm:p-6">
          <ul role="list" class="grid grid-cols-2 gap-x-0 md:gap-x-4 gap-y-8 sm:grid-cols-2 sm:gap-x-6 lg:grid-cols-2 xl:gap-x-8" data-controller="vote"<% unless @vote_throttle %> data-action="keyup@window->vote#keypress"<% end %>>
            
            <li class="relative item_first">
              <%= link_to votes_battle_path(@item_first.id, @item_last.id), 'data-action': 'click->vote#toggle', 'data-vote-target': 'itemFirst' do %>
              <div class="group block w-full aspect-w-1 aspect-h-1 rounded-3xl bg-white border-8 border-transparent hover:border-green-500 overflow-hidden">

                <div data-vote-target="element" class="voted opacity-0 bg-black bg-opacity-70 flex justify-center items-center transition-all duration-100"><i class="fa-duotone fa-circle-check text-9xl text-green-500"></i></div>

                
                <img src="<%=@item_first.image_url%>" alt="" class="object-cover pointer-events-none <%= 'bg-gray-100' if @item_first.background_color.blank? %>" <%= %Q[style=background-color:##{@item_first.background_color}] if @item_first.background_color.present? %>>
                
                
              </div>
              <% end %>
              <p class="px-0 pb-3 md:px-3 text-sm text-center text-gray-500 font-medium hover:text-indigo-500"><a href="<%= collection_asset_url(@item_first.collection.slug, @item_first.token_id) %>" data-turbo-frame="_top"><%= @item_first.formatted_name %> <i class="fa-duotone fa-square-up-right"></i></a></p>
            </li>

            <li class="relative item_last">
              <%= link_to votes_battle_path(@item_last.id, @item_first.id), 'data-action': 'click->vote#toggle', 'data-vote-target': 'itemLast' do %>
              <div class="group block w-full aspect-w-1 aspect-h-1 rounded-3xl bg-white border-8 border-transparent hover:border-green-500 overflow-hidden">

                <div data-vote-target="element" class="voted opacity-0 bg-black bg-opacity-70 flex justify-center items-center transition-all duration-100"><i class="fa-duotone fa-circle-check text-9xl text-green-500"></i></div>
                
               
                <img src="<%=@item_last.image_url%>" alt="" class="object-cover pointer-events-none <%= 'bg-gray-100' if @item_last.background_color.blank? %>" <%= %Q[style=background-color:##{@item_last.background_color}] if @item_last.background_color.present? %>>
                
                
              </div>
              <% end %>
              <p class="px-0 pb-3 md:px-3 text-sm text-center text-gray-500 font-medium hover:text-indigo-500"><a href="<%= collection_asset_url(@item_last.collection.slug, @item_last.token_id) %>" data-turbo-frame="_top"><%= @item_last.formatted_name %> <i class="fa-duotone fa-square-up-right"></i></a></p>
            </li>

          </ul>
        </div>
    

      </div>



    </div>
  </div>
  <% end %>
</main>